In [2]:
%pip install scikit-learn

  Using cached scikit_learn-1.5.2-cp312-cp312-win_amd64.whl.metadata (13 kB)
  Using cached scipy-1.14.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.2-cp312-cp312-win_amd64.whl (11.0 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.14.1-cp312-cp312-win_amd64.whl (44.5 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import mysql.connector

In [3]:
# Conexión a la base de datos
conexion = mysql.connector.connect(
    host="127.0.0.1",
    user="root",  
    password="Mysql123",
    database="yfinance"  
)

# Carga de datos desde una consulta SQL a un DataFrame
query = "SELECT precios_historicos.precio_apertura,precios_historicos.precio_cierre,precios_historicos.maximo,precios_historicos.minimo,precios_historicos.volumen,empresas_sp500.sector,empresas_sp500.industria FROM precios_historicos INNER JOIN empresas_sp500 ON precios_historicos.id_empresa = empresas_sp500.id_empresa;"
df = pd.read_sql(query, conexion)





C:\Users\Rober\AppData\Local\Temp\ipykernel_7132\462899246.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexion)


In [16]:
conexion = mysql.connector.connect(
    host="127.0.0.1",
    user="root",  
    password="Mysql123",
    database="yfinance")

query = "SELECT precios_historicos.precio_apertura,precios_historicos.precio_cierre,precios_historicos.maximo,precios_historicos.minimo,precios_historicos.volumen,empresas_sp500.sector,empresas_sp500.industria FROM precios_historicos INNER JOIN empresas_sp500 ON precios_historicos.id_empresa = empresas_sp500.id_empresa;"
empresas_df = pd.read_sql(query, conexion)


empresas_df.head(5)

C:\Users\Rober\AppData\Local\Temp\ipykernel_7132\2941051003.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  empresas_df = pd.read_sql(query, conexion)


precio_apertura  precio_cierre   maximo   minimo  volumen       sector  \
0          20.1681        19.8138  20.2600  19.7482  2599386  Industrials   
1          19.4989        19.0265  19.9057  19.0265  3245705  Industrials   
2          19.1315        19.5776  20.2075  19.1315  4424482  Industrials   
3          19.8007        21.1523  21.5197  19.8007  7147057  Industrials   
4          21.2310        21.5721  21.7952  20.9817  4905035  Industrials   

                  industria  
0  Industrial Conglomerates  
1  Industrial Conglomerates  
2  Industrial Conglomerates  
3  Industrial Conglomerates  
4  Industrial Conglomerates

In [17]:
empresas_df['cluster'] = np.nan

In [ ]:
# Simular datos de ejemplo
np.random.seed(42)

empresas_df = pd.DataFrame(empresas_df, columns=['precio_apertura', 'precio_cierre', 'maximo', 'minimo', 'volumen'])
x = empresas_df[['precio_apertura','precio_cierre','maximo','minimo','volumen']]


# Ejecutar K-Means para agrupar las acciones
kmeans = KMeans(n_clusters=5, random_state=42)
y = kmeans.fit_predict(x)
empresas_df['Cluster'] = y


print(df.head())  # Visualizar las características y el cluster asignado

conexion.close()

   precio_apertura  precio_cierre   maximo   minimo  volumen       sector  \
0          20.1681        19.8138  20.2600  19.7482  2599386  Industrials   
1          19.4989        19.0265  19.9057  19.0265  3245705  Industrials   
2          19.1315        19.5776  20.2075  19.1315  4424482  Industrials   
3          19.8007        21.1523  21.5197  19.8007  7147057  Industrials   
4          21.2310        21.5721  21.7952  20.9817  4905035  Industrials   

                  industria  
0  Industrial Conglomerates  
1  Industrial Conglomerates  
2  Industrial Conglomerates  
3  Industrial Conglomerates  
4  Industrial Conglomerates  


In [22]:
#convertir Y en unidimensional#
y = empresas_df['Cluster'].values.ravel()

# Dividir el conjunto de datos en entrenamiento y prueba (80% entrenamiento, 20% prueba)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print("Datos preparados:")
print(f"Tamaño de X_train: {X_train.shape}, X_test: {X_test.shape}")
print(f"Tamaño de y_train: {y_train.shape}, y_test: {y_test.shape}")

Datos preparados:
Tamaño de X_train: (2205567, 5), X_test: (551392, 5)
Tamaño de y_train: (2205567,), y_test: (551392,)


In [23]:
print(y.shape)

(2756959,)


In [25]:
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Crear y entrenar el modelo
modelo = RandomForestClassifier(n_estimators=20,max_depth=10,max_features= 'sqrt', random_state=42)
modelo.fit(X_train, y_train) #Tuve que reducir significativamente los parámetros por motivo de la RAM 

# Hacer predicciones en los datos de prueba
pca = PCA(n_components=5)  # Reduce a 5 componentes principales
X_test_reduced = pca.fit_transform(X_test)
y_pred = modelo.predict(X_test_reduced)

print("Dimensiones de y_test:", y_test.shape)
print("Dimensiones de y_pred:", y_pred.shape)

# Convertir y_test a un array de NumPy
y_test = np.array(y_test).ravel()
y_pred = np.array(y_pred).ravel()


print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))



c:\Users\Rober\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Dimensiones de y_test: (551392,)
Dimensiones de y_pred: (551392,)
Matriz de Confusión:
[[     0      0      0   9357      0]
 [     0      0      0    575      0]
 [     0      0      0   1593      0]
 [     0      0      0 539784      0]
 [     0      0      0     83      0]]

Reporte de Clasificación:


c:\Users\Rober\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00      9357
           1       0.00      0.00      0.00       575
           2       0.00      0.00      0.00      1593
           3       0.98      1.00      0.99    539784
           4       0.00      0.00      0.00        83

    accuracy                           0.98    551392
   macro avg       0.20      0.20      0.20    551392
weighted avg       0.96      0.98      0.97    551392



c:\Users\Rober\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Rober\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
